<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ESCP 8082 R Labs - 6&nbsp; Measurement Invariance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./reliability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ESCP 8082 R Labs</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.twitter.com/winterstat" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.github.com/winterstat" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./measurementinvariance.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measurement Invariance</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gettingstarted.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confirmatoryfactoranalysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Confirmatory Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exploratoryfactoranalysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploratory Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reliability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measurementinvariance.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measurement Invariance</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#loading-the-r-packages" id="toc-loading-the-r-packages" class="nav-link active" data-scroll-target="#loading-the-r-packages"><span class="header-section-number">6.1</span> Loading the R packages</a></li>
  <li><a href="#loading-data-into-our-environment" id="toc-loading-data-into-our-environment" class="nav-link" data-scroll-target="#loading-data-into-our-environment"><span class="header-section-number">6.2</span> Loading data into our environment</a></li>
  <li><a href="#the-theoretical-measurement-model" id="toc-the-theoretical-measurement-model" class="nav-link" data-scroll-target="#the-theoretical-measurement-model"><span class="header-section-number">6.3</span> The Theoretical Measurement Model</a></li>
  <li><a href="#step-1-configural-invariance" id="toc-step-1-configural-invariance" class="nav-link" data-scroll-target="#step-1-configural-invariance"><span class="header-section-number">6.4</span> Step 1: Configural Invariance</a>
  <ul class="collapse">
  <li><a href="#if-configural-invariance-is-not-supported" id="toc-if-configural-invariance-is-not-supported" class="nav-link" data-scroll-target="#if-configural-invariance-is-not-supported">If configural invariance is not supported</a></li>
  </ul></li>
  <li><a href="#step-2-metric-invariance" id="toc-step-2-metric-invariance" class="nav-link" data-scroll-target="#step-2-metric-invariance"><span class="header-section-number">6.5</span> Step 2: Metric Invariance</a></li>
  <li><a href="#step-3-scalar-invariance" id="toc-step-3-scalar-invariance" class="nav-link" data-scroll-target="#step-3-scalar-invariance"><span class="header-section-number">6.6</span> Step 3: Scalar Invariance</a>
  <ul class="collapse">
  <li><a href="#step-3b-partial-scalar-invariance" id="toc-step-3b-partial-scalar-invariance" class="nav-link" data-scroll-target="#step-3b-partial-scalar-invariance">Step 3B: Partial Scalar Invariance</a></li>
  </ul></li>
  <li><a href="#step-4-strict-invariance-optional" id="toc-step-4-strict-invariance-optional" class="nav-link" data-scroll-target="#step-4-strict-invariance-optional"><span class="header-section-number">6.7</span> Step 4 Strict Invariance (Optional)</a></li>
  <li><a href="#step-5-interpreting-the-mean-difference-between-public-and-private-sector-groups-optional" id="toc-step-5-interpreting-the-mean-difference-between-public-and-private-sector-groups-optional" class="nav-link" data-scroll-target="#step-5-interpreting-the-mean-difference-between-public-and-private-sector-groups-optional"><span class="header-section-number">6.8</span> Step 5: Interpreting the Mean Difference between Public and Private Sector Groups (Optional)</a>
  <ul class="collapse">
  <li><a href="#step-5-method-1-for-making-mean-differences-comparable" id="toc-step-5-method-1-for-making-mean-differences-comparable" class="nav-link" data-scroll-target="#step-5-method-1-for-making-mean-differences-comparable">Step 5: Method 1 for making mean differences comparable</a></li>
  <li><a href="#step-5-method-2-for-making-mean-differences-comparable" id="toc-step-5-method-2-for-making-mean-differences-comparable" class="nav-link" data-scroll-target="#step-5-method-2-for-making-mean-differences-comparable">Step 5: Method 2 for making mean differences comparable</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.9</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measurement Invariance</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="loading-the-r-packages" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="loading-the-r-packages"><span class="header-section-number">6.1</span> Loading the R packages</h2>
<p>In this lab, we will use the lavaan, semTools, and ggplot2 packages, which we have already installed in earlier labs. So, we can simply get those packages from the R package library:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semTools)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-data-into-our-environment" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="loading-data-into-our-environment"><span class="header-section-number">6.2</span> Loading data into our environment</h2>
<p>For this lab, we will use a dataset that contains 3811 item responses to 10 items about financial well-being. You can download the data by right-clicking this link and selecting “Save Link As…” in the drop-down menu: <a href="data/finance.csv">data/finance.csv</a>. Make sure to save it in the folder you are using for this class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>finance <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/finance.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can look at the variables in the dataset using <code>describe()</code> from the psych package. In addition to the 10 items, the dataset also includes a variable denoting whether a participant worked in the public or private sector.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(finance, <span class="at">skew =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        vars    n mean   sd median min max range   se
item1      1 3811 2.89 1.23      3   1   5     4 0.02
item2      2 3811 3.09 1.10      3   1   5     4 0.02
item3      3 3811 2.69 1.19      3   1   5     4 0.02
item4      4 3811 3.15 1.04      3   1   5     4 0.02
item5      5 3811 2.87 1.24      3   1   5     4 0.02
item6      6 3811 3.25 1.13      3   1   5     4 0.02
item7      7 3811 2.48 1.19      2   1   5     4 0.02
item8      8 3811 3.27 1.25      3   1   5     4 0.02
item9      9 3811 2.22 1.14      2   1   5     4 0.02
item10    10 3811 2.83 1.13      3   1   5     4 0.02
sector*   11 3811 1.55 0.50      2   1   2     1 0.01</code></pre>
</div>
</div>
<p>These items make up the Financial Well-Being scale, which was developed by the Consumer Financial Protection Bureau (CFPB):</p>
<ol type="1">
<li>I could handle a major unexpected expense (P)</li>
<li>I am securing my financial future (P)</li>
<li>Because of my money situation, I will never have the things I want in life (N)</li>
<li>I can enjoy life because of the way I’m managing my money (P)</li>
<li>I am just getting by financially (N)</li>
<li>I am concerned that the money I have or will save won’t last (N)</li>
<li>Giving a gift would put a strain on my finances for the month (N)</li>
<li>I have money left over at the end of the month (P)</li>
<li>I am behind with my finances (N)</li>
<li>My finances control my life (N)</li>
</ol>
<p>The items measure positive (P) and negative (N) financial well-being.</p>
</section>
<section id="the-theoretical-measurement-model" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="the-theoretical-measurement-model"><span class="header-section-number">6.3</span> The Theoretical Measurement Model</h2>
<p>Next, we will set up the theoretical measurement model representing the hypothesized internal structure of this measure. In this case, the construct of financial well-being is represented by two correlated sub-constructs: financial stability and financial instability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-factor CFA model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>financemodel <span class="ot">&lt;-</span> <span class="st">"positive =~ item1 + item2 + item4 + item8</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="st">                 negative =~ item3 + item5 + item6 + item7 + item9 + item10"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-1-configural-invariance" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="step-1-configural-invariance"><span class="header-section-number">6.4</span> Step 1: Configural Invariance</h2>
<p>To test measurement invariance (MI), we will use the <code>lavaan</code> package. First, we will assess configural invariance, which we can do using the code below. The main difference from previous CFAs is that we now use the <code>group = "sector"</code> argument to denote which variable in our data denotes what group a participant is a member of. In addition, we will tell lavaan to scale the latent factors so they have a mean of 0 and a standard deviation of 1, using the <code>std.lv = TRUE</code> argument (note that there are other methods for scaling the latent variable, but going into those technical details is beyond the scope of this class):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Configural model</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>config <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">"sector"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To evaluate whether configural invariance holds, we can look at the summary output. In this case, I’m mostly interested in looking at the fit of the model to the data, so we will use <code>estimates = F</code> to omit the parameter estimates from the summary output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(config, <span class="at">fit.measures =</span> T, <span class="at">estimates =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.17 ended normally after 27 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        62

  Number of observations per group:                   
    public                                        2110
    private                                       1701

Model Test User Model:
                                                      
  Test statistic                               875.170
  Degrees of freedom                                68
  P-value (Chi-square)                           0.000
  Test statistic for each group:
    public                                     465.024
    private                                    410.146

Model Test Baseline Model:

  Test statistic                             20856.369
  Degrees of freedom                                90
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.961
  Tucker-Lewis Index (TLI)                       0.949

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -49649.240
  Loglikelihood unrestricted model (H1)     -49211.655
                                                      
  Akaike (AIC)                               99422.480
  Bayesian (BIC)                             99809.711
  Sample-size adjusted Bayesian (SABIC)      99612.704

Root Mean Square Error of Approximation:

  RMSEA                                          0.079
  90 Percent confidence interval - lower         0.074
  90 Percent confidence interval - upper         0.084
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.359

Standardized Root Mean Square Residual:

  SRMR                                           0.031</code></pre>
</div>
</div>
<p>Overall, the fit of the model to the data, allowing all parameters to be freely estimated across groups, is decent: CFI &gt; .95, TLI = .95, RMSEA = .079, 95% CI [.074, .084] SRMR &lt; .08. Not ideal in terms of RMSEA, but otherwise okay. More importantly, this output shows us what part of the overall Model Chi-square is stemming from each of the two groups (under <code>Test statistic for each group</code>). If those two numbers are relatively equal, then the model fits about equally well to each group’s data. If you notice that the Chi-square contribution is much larger for one group than the other, it is an indication that you may not be able to conclude that there is configural invariance. In this case, both groups contribute about equally to the total Chi-square, indicating similar model-data fit across groups.</p>
<section id="if-configural-invariance-is-not-supported" class="level3">
<h3 class="anchored" data-anchor-id="if-configural-invariance-is-not-supported">If configural invariance is not supported</h3>
<p>If configural invariance is not supported, then you can start your investigation by looking at the estimates across each group to see if there are noticeable issues (e.g., a lot of low factor loadings in one group). You can follow this investigation up by running separate EFAs for each group, to examine what kind of factor structure emerges for each group. The code below shows you how to start this investigation for this example dataset, but I do not include the output to reduce the length of this (already lengthy) lab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine parameter estimates</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(config)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data is two</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>public <span class="ot">&lt;-</span> <span class="fu">subset</span>(finance, sector <span class="sc">==</span> <span class="st">"public"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>private <span class="ot">&lt;-</span> <span class="fu">subset</span>(finance, sector <span class="sc">==</span> <span class="st">"private"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Run parallel analysis for each group </span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># (can be followed up by full EFA examination)</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(public[,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">fa =</span> <span class="st">"fa"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(private[,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="at">fa =</span> <span class="st">"fa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="step-2-metric-invariance" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="step-2-metric-invariance"><span class="header-section-number">6.5</span> Step 2: Metric Invariance</h2>
<p>Next, we will estimate the metric invariance model. To do so, we again use the <code>cfa()</code> function and specify our grouping variable and latent factor scale. In addition, we will add <code>group.equal = "loadings"</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Metric model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>metric <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">group.equal =</span> <span class="st">"loadings"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see if the metric model fits the data significantly worse than the configural model, we will use the <code>compareFit()</code> function from the <code>semTools</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(config, metric))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

       Df   AIC   BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)
config 68 99422 99810 875.17                                       
metric 76 99417 99754 885.35     10.179 0.011957       8     0.2527

####################### Model Fit Indices ###########################
          chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
config 875.170† 68   .000 .079  .961† .949  .031† 99422.480  99809.711 
metric 885.349  76   .000 .075† .961  .954† .033  99416.660† 99753.925†

################## Differences in Fit Indices #######################
                df  rmsea cfi   tli  srmr    aic     bic
metric - config  8 -0.004   0 0.005 0.002 -5.821 -55.786</code></pre>
</div>
</div>
<p>The null hypothesis that we’re testing is that the fit of the metric and configural model is equivalent (i.e., adding equality constraints to the loadings does not make the model fit worse). Thus, if the <em>p</em>-value associated with the Chi-square difference test is &gt; .05, we can retain that null hypothesis and conclude that metric invariance holds for these data. If the <em>p</em>-value associated with the Chi-square difference test is &lt; .05, then we need to reject the null hypothesis and conclude that the metric invariance model fit the data significantly worse, and so metric invariance does not hold.</p>
<p>Note: If any loadings were found to be non-invariant (i.e., there is partial metric invariance), then the intercepts of those items also need to be estimated freely across groups in the next step. In other words, you start your investigation with a model that is already partially invariant at the scalar level (see below how to run partial invariance models).</p>
</section>
<section id="step-3-scalar-invariance" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="step-3-scalar-invariance"><span class="header-section-number">6.6</span> Step 3: Scalar Invariance</h2>
<p>Next, we will evaluate if scalar invariance holds for our data. To do so, we simply add the intercepts to the <code>group.equal = c("loadings","intercepts")</code> argument:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scalar model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>scalar <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we compare the scalar model’s fit to the fit of the metric model, to see if adding the equality constraints on the intercepts results in significantly worse fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(metric, scalar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

       Df   AIC   BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)    
metric 76 99417 99754 885.35                                           
scalar 84 99453 99740 937.72     52.371 0.053951       8  1.427e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

####################### Model Fit Indices ###########################
          chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
metric 885.349† 76   .000 .075  .961† .954  .033† 99416.660† 99753.925 
scalar 937.720  84   .000 .073† .959  .956† .034  99453.030  99740.330†

################## Differences in Fit Indices #######################
                df  rmsea    cfi   tli  srmr    aic     bic
scalar - metric  8 -0.002 -0.002 0.002 0.001 36.371 -13.595</code></pre>
</div>
</div>
<p>From the Chi-square difference test above, we can see that the scalar model fit the data significantly worse than the metric model. This means that, at least for some items, the expected response for those with an average (i.e., 0) score on the latent factor differs across groups.</p>
<section id="step-3b-partial-scalar-invariance" class="level3">
<h3 class="anchored" data-anchor-id="step-3b-partial-scalar-invariance">Step 3B: Partial Scalar Invariance</h3>
<p>To easily get an overview of what equality constraints should be released to result in the largest improvement in model fit, we can use the <code>lavTestScore</code> function from the <code>lavaan</code> package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust the model for partial invariance testing</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestScore</span>(scalar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$test

total score test:

   test     X2 df p.value
1 score 62.622 20       0

$uni

univariate score tests:

     lhs op   rhs     X2 df p.value
1   .p1. == .p36.  0.125  1   0.724
2   .p2. == .p37.  0.594  1   0.441
3   .p3. == .p38.  0.323  1   0.570
4   .p4. == .p39.  0.327  1   0.567
5   .p5. == .p40.  1.733  1   0.188
6   .p6. == .p41.  1.909  1   0.167
7   .p7. == .p42.  1.219  1   0.270
8   .p8. == .p43.  2.986  1   0.084
9   .p9. == .p44.  2.129  1   0.144
10 .p10. == .p45.  0.011  1   0.916
11 .p24. == .p59. 15.296  1   0.000
12 .p25. == .p60.  0.215  1   0.643
13 .p26. == .p61. 16.963  1   0.000
14 .p27. == .p62.  0.257  1   0.612
15 .p28. == .p63.  9.145  1   0.002
16 .p29. == .p64.  0.445  1   0.505
17 .p30. == .p65.  0.101  1   0.751
18 .p31. == .p66. 21.472  1   0.000
19 .p32. == .p67.  1.433  1   0.231
20 .p33. == .p68.  4.348  1   0.037</code></pre>
</div>
</div>
<p>To figure out what equality constraints map onto which item’s intercept, we can look at the parameter table of the scalar model. In the code below, I filter the output to only include intercept parameters (<code>op = "~1"</code>), only show parameters from group 2 (<code>group == 2</code>) and then to only include certain columns and rows of that output. This was mostly done to keep this PDF from becoming too large. You don’t need to do any of this filtering yourself.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To view the entire parameter table, simply use this code </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (remove the hashtag in front of the next line):</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># parTable(scalar)</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># To filter the output (this literal code will only work for </span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># this example):</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="fu">parTable</span>(scalar), op <span class="sc">==</span> <span class="st">"~1"</span> <span class="sc">&amp;</span> group <span class="sc">==</span> <span class="dv">2</span>)[,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">11</span><span class="sc">:</span><span class="dv">15</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id      lhs op rhs label plabel start    est    se
59 59    item1 ~1     .p24.  .p59. 2.733  2.994 0.025
60 60    item2 ~1     .p25.  .p60. 2.978  3.173 0.022
61 61    item4 ~1     .p26.  .p61. 3.093  3.232 0.021
62 62    item8 ~1     .p27.  .p62. 3.162  3.370 0.025
63 63    item3 ~1     .p28.  .p63. 2.708  2.638 0.024
64 64    item5 ~1     .p29.  .p64. 2.931  2.820 0.024
65 65    item6 ~1     .p30.  .p65. 3.301  3.203 0.022
66 66    item7 ~1     .p31.  .p66. 2.600  2.432 0.024
67 67    item9 ~1     .p32.  .p67. 2.256  2.174 0.022
68 68   item10 ~1     .p33.  .p68. 2.855  2.785 0.022
69 69 positive ~1            .p69. 0.000 -0.217 0.035
70 70 negative ~1            .p70. 0.000  0.121 0.035</code></pre>
</div>
</div>
<p>In the table above, we can see the the intercept of Item 7 is associated with the largest potential improvement in model fit. So, we estimate a partial scalar invariance model. To release the equality constraint for the intercept of Item 7, we add the <code>group.partial = c("item7 ~ 1")</code> argument. Once the model is estimated, we will compare its fit to the metric model, to see if we need to release additional intercept parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scalar2 <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">"sector"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>), </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.partial =</span> <span class="fu">c</span>(<span class="st">"item7 ~ 1"</span>)) </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># for a loading, group.partial would look like: "negative =~ item7"</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(metric, scalar2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

        Df   AIC   BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)    
metric  76 99417 99754 885.35                                           
scalar2 83 99434 99727 916.21     30.863 0.042297       7   6.59e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

####################### Model Fit Indices ###########################
           chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
metric  885.349† 76   .000 .075  .961† .954  .033† 99416.660† 99753.925 
scalar2 916.212  83   .000 .073† .960  .956† .034  99433.523  99727.068†

################## Differences in Fit Indices #######################
                 df  rmsea    cfi   tli  srmr    aic     bic
scalar2 - metric  7 -0.002 -0.001 0.003 0.001 16.863 -26.857</code></pre>
</div>
</div>
<p>The fit of the first partial scalar model is still worse than the metric model. So, we need to release additional equality constraints. After examining the modification indices again, we release the equality constraint of Item 4’s intercept, estimate the model again, and compare this second partial model to the metric model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust the model for partial invariance testing</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestScore</span>(scalar2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$test

total score test:

   test     X2 df p.value
1 score 41.208 19   0.002

$uni

univariate score tests:

     lhs op   rhs     X2 df p.value
1   .p1. == .p36.  0.125  1   0.723
2   .p2. == .p37.  0.594  1   0.441
3   .p3. == .p38.  0.323  1   0.570
4   .p4. == .p39.  0.327  1   0.567
5   .p5. == .p40.  2.131  1   0.144
6   .p6. == .p41.  1.823  1   0.177
7   .p7. == .p42.  1.128  1   0.288
8   .p8. == .p43.  1.924  1   0.165
9   .p9. == .p44.  1.885  1   0.170
10 .p10. == .p45.  0.045  1   0.832
11 .p24. == .p59. 15.297  1   0.000
12 .p25. == .p60.  0.215  1   0.643
13 .p26. == .p61. 16.964  1   0.000
14 .p27. == .p62.  0.257  1   0.612
15 .p28. == .p63.  2.901  1   0.089
16 .p29. == .p64.  2.900  1   0.089
17 .p30. == .p65.  1.991  1   0.158
18 .p32. == .p67.  0.000  1   0.989
19 .p33. == .p68.  0.840  1   0.359</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>scalar3 <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>), </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.partial =</span> <span class="fu">c</span>(<span class="st">"item7 ~ 1"</span>, <span class="st">"item4 ~ 1"</span>))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(metric, scalar3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

        Df   AIC   BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
metric  76 99417 99754 885.35                                        
scalar3 82 99418 99718 899.16     13.812 0.02614       6     0.0318 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

####################### Model Fit Indices ###########################
           chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
metric  885.349† 76   .000 .075  .961† .954  .033† 99416.660† 99753.925 
scalar3 899.161  82   .000 .072† .961  .957† .033  99418.472  99718.263†

################## Differences in Fit Indices #######################
                 df  rmsea cfi   tli srmr   aic     bic
scalar3 - metric  6 -0.002   0 0.003    0 1.812 -35.661</code></pre>
</div>
</div>
<p>The fit of this partial model is still worse than the metric model. So, we need to release additional equality constraints. After examining the modification indices again, we release the equality constraint of Item 1’s intercept, estimate the model again, and compare this second partial model to the metric model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust the model for partial invariance testing</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestScore</span>(scalar3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$test

total score test:

   test     X2 df p.value
1 score 24.243 18   0.147

$uni

univariate score tests:

     lhs op   rhs    X2 df p.value
1   .p1. == .p36. 0.276  1   0.599
2   .p2. == .p37. 0.946  1   0.331
3   .p3. == .p38. 1.352  1   0.245
4   .p4. == .p39. 0.127  1   0.722
5   .p5. == .p40. 2.132  1   0.144
6   .p6. == .p41. 1.826  1   0.177
7   .p7. == .p42. 1.128  1   0.288
8   .p8. == .p43. 1.919  1   0.166
9   .p9. == .p44. 1.883  1   0.170
10 .p10. == .p45. 0.046  1   0.830
11 .p24. == .p59. 6.551  1   0.010
12 .p25. == .p60. 0.744  1   0.388
13 .p27. == .p62. 3.488  1   0.062
14 .p28. == .p63. 2.901  1   0.089
15 .p29. == .p64. 2.900  1   0.089
16 .p30. == .p65. 1.991  1   0.158
17 .p32. == .p67. 0.000  1   0.989
18 .p33. == .p68. 0.840  1   0.359</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>scalar4 <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>), </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.partial =</span> <span class="fu">c</span>(<span class="st">"item7 ~ 1"</span>, <span class="st">"item4 ~ 1"</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"item1 ~ 1"</span>))</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(metric, scalar4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

        Df   AIC   BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)
metric  76 99417 99754 885.35                                       
scalar4 81 99414 99720 892.61     7.2647 0.015418       5     0.2017

####################### Model Fit Indices ###########################
           chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
metric  885.349† 76   .000 .075  .961† .954  .033† 99416.660  99753.925 
scalar4 892.614  81   .000 .073† .961  .957† .033  99413.925† 99719.961†

################## Differences in Fit Indices #######################
                 df  rmsea cfi   tli srmr    aic     bic
scalar4 - metric  5 -0.002   0 0.003    0 -2.735 -33.964</code></pre>
</div>
</div>
<p>This time, the fit of the partial scalar model is not worse than that of the metric model (<em>p</em> &gt; .05), so we can conclude that partial scalar invariance holds for these data.</p>
</section>
</section>
<section id="step-4-strict-invariance-optional" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="step-4-strict-invariance-optional"><span class="header-section-number">6.7</span> Step 4 Strict Invariance (Optional)</h2>
<p>Finally, we can examine strict invariance by constraining the residuals to be equal across groups. To do so, we simply add the residuals to the <code>group.equal = c("loadings","intercepts","residuals)</code> argument. Note that we keep the partial intercepts from the previous step and need to add partial residuals for those items.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Strict model</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>strict <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>,<span class="st">"residuals"</span>), </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">group.partial =</span> <span class="fu">c</span>(<span class="st">"item7 ~ 1"</span>, <span class="st">"item4 ~ 1"</span>, </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"item1 ~ 1"</span>,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"item7 ~~ item7"</span>, </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"item4 ~~ item4"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"item1 ~~ item1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similar to previous steps, we can compare the fit of this model to the previous (partial scalar) model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(scalar4, strict))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

        Df   AIC   BIC  Chisq Chisq diff    RMSEA Df diff Pr(&gt;Chisq)   
scalar4 81 99414 99720 892.61                                          
strict  88 99423 99686 915.96     23.351 0.035012       7    0.00148 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

####################### Model Fit Indices ###########################
           chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
scalar4 892.614† 81   .000 .073  .961† .957  .033† 99413.925† 99719.961 
strict  915.965  88   .000 .070† .960  .959† .033  99423.276  99685.593†

################## Differences in Fit Indices #######################
                 df  rmsea    cfi   tli srmr   aic     bic
strict - scalar4  7 -0.002 -0.001 0.003    0 9.351 -34.368</code></pre>
</div>
</div>
</section>
<section id="step-5-interpreting-the-mean-difference-between-public-and-private-sector-groups-optional" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="step-5-interpreting-the-mean-difference-between-public-and-private-sector-groups-optional"><span class="header-section-number">6.8</span> Step 5: Interpreting the Mean Difference between Public and Private Sector Groups (Optional)</h2>
<p>As we’ve been able to establish partial scalar invariance, we can compare the latent factor means across groups. To do so, we use the final partial scalar model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="fu">parameterEstimates</span>(scalar4), </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>       (op <span class="sc">==</span> <span class="st">"~1"</span> <span class="sc">&amp;</span> (lhs <span class="sc">==</span> <span class="st">"positive"</span> <span class="sc">|</span> lhs <span class="sc">==</span> <span class="st">"negative"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        lhs op rhs block group label    est    se      z pvalue ci.lower
34 positive ~1         1     1        0.000 0.000     NA     NA    0.000
35 negative ~1         1     1        0.000 0.000     NA     NA    0.000
69 positive ~1         2     2       -0.216 0.037 -5.823  0.000   -0.289
70 negative ~1         2     2        0.086 0.035  2.425  0.015    0.016
   ci.upper
34    0.000
35    0.000
69   -0.143
70    0.155</code></pre>
</div>
</div>
<p>To help with interpretation, the means of the latent factors in the first group (Public) are fixed to 0 and their variances are fixed to one. This constraint means that the freely estimated latent means in the second group (Private) can be interpreted as “relative to” the first group. In the output, we can see that the positive financial well-being mean is negative (and significant) whereas the negative financial well-being mean is positive (and significant). However, the factors’ variances in this group are not equal to 1 (they are slightly smaller) and so these means are not measured on the same scale as the means of the Public sector group. There are several ways to make the means comparable.</p>
<section id="step-5-method-1-for-making-mean-differences-comparable" class="level3">
<h3 class="anchored" data-anchor-id="step-5-method-1-for-making-mean-differences-comparable">Step 5: Method 1 for making mean differences comparable</h3>
<p>The first is to evaluate whether the latent factor variances can be constrained to equivalence without resulting in worse model fit. This would place both groups’ factors on the standardized scale (variance or <em>sd</em> = 1) and mean differences can be interpreted in terms of standard deviation units. To test this model, we can use the following code, adding <code>"lv.variances"</code> to the <code>group.equal</code> argument and then testing whether the resulting model fit significantly worse than the partial scalar model. Note that we do not have to meet the strict invariance level to test this latent variance level of invariance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lvvar <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> financemodel, <span class="at">data =</span> finance, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">group =</span> <span class="st">"sector"</span>, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">std.lv =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>,<span class="st">"intercepts"</span>, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"lv.variances"</span>), </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">group.partial =</span> <span class="fu">c</span>(<span class="st">"item7 ~ 1"</span>, <span class="st">"item4 ~ 1"</span>, </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"item1 ~ 1"</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">compareFit</span>(scalar4, lvvar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

        Df   AIC   BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
scalar4 81 99414 99720 892.61                                    
lvvar   83 99410 99704 893.05    0.43956     0       2     0.8027

####################### Model Fit Indices ###########################
           chisq df pvalue rmsea   cfi   tli  srmr        aic        bic
scalar4 892.614† 81   .000 .073  .961  .957  .033† 99413.925  99719.961 
lvvar   893.053  83   .000 .072† .961† .958† .034  99410.364† 99703.910†

################## Differences in Fit Indices #######################
                df  rmsea cfi   tli  srmr   aic     bic
lvvar - scalar4  2 -0.001   0 0.001 0.001 -3.56 -16.052</code></pre>
</div>
</div>
<p>Constraining the latent factor variances to equivalence across groups does not result in significantly worse model fit (<em>p</em> = .803), so we can use the estimates from the <code>lvvar</code> output to interpret mean differences between the Public and Private sector groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="fu">parameterEstimates</span>(lvvar), </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>       (op <span class="sc">==</span> <span class="st">"~1"</span> <span class="sc">&amp;</span> (lhs <span class="sc">==</span> <span class="st">"positive"</span> <span class="sc">|</span> lhs <span class="sc">==</span> <span class="st">"negative"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        lhs op rhs block group label    est    se      z pvalue ci.lower
34 positive ~1         1     1        0.000 0.000     NA     NA    0.000
35 negative ~1         1     1        0.000 0.000     NA     NA    0.000
69 positive ~1         2     2       -0.217 0.037 -5.829  0.000   -0.290
70 negative ~1         2     2        0.087 0.036  2.422  0.015    0.016
   ci.upper
34    0.000
35    0.000
69   -0.144
70    0.157</code></pre>
</div>
</div>
<p>Based on the results above, we can conclude that positive financial well-being is .22 standard deviations (<em>SE</em> = .04) lower for those working in the Private sector compared to those working in the Public section (<em>p</em> &lt; .001). In addition, negative financial well-being is .09 standard deviations (<em>SE</em> = .04) higher for those working in the Private sector compared to those working in the Public section (<em>p</em> = .015).</p>
</section>
<section id="step-5-method-2-for-making-mean-differences-comparable" class="level3">
<h3 class="anchored" data-anchor-id="step-5-method-2-for-making-mean-differences-comparable">Step 5: Method 2 for making mean differences comparable</h3>
<p>If the previous method would have shown that factor variances are not comparable, then we could have used the formula for standardized mean differences (Cohen’s <em>D</em>) to compute mean differences.</p>
<p><span class="math display">\[Cohen's D = \frac{(m_1 - m_2)}{\sqrt\sigma^2}\]</span></p>
<p>To do so, we need the latent factor means and variances from the partial scalar model. We already know that the means and variances in the first group are 0 and 1 respectively, so we only need to know the means and variances for group 2 (i.e., Private sector):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="fu">parameterEstimates</span>(scalar4), </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>       (group <span class="sc">==</span> <span class="dv">2</span> <span class="sc">&amp;</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>          (op <span class="sc">==</span> <span class="st">"~1"</span> <span class="sc">|</span> op <span class="sc">==</span> <span class="st">"~~"</span>) <span class="sc">&amp;</span> (lhs <span class="sc">==</span> <span class="st">"positive"</span> <span class="sc">|</span> lhs <span class="sc">==</span> <span class="st">"negative"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        lhs op      rhs block group label    est    se       z pvalue ci.lower
56 positive ~~ positive     2     2        0.973 0.051  19.042  0.000    0.873
57 negative ~~ negative     2     2        0.967 0.051  18.882  0.000    0.867
58 positive ~~ negative     2     2       -0.818 0.042 -19.583  0.000   -0.899
69 positive ~1              2     2       -0.216 0.037  -5.823  0.000   -0.289
70 negative ~1              2     2        0.086 0.035   2.425  0.015    0.016
   ci.upper
56    1.074
57    1.068
58   -0.736
69   -0.143
70    0.155</code></pre>
</div>
</div>
<p>When variances are not equal across groups, we can compute separate standardized mean differences using each group’s variance in the denominator, which will give us a range of plausible mean difference effect sizes (not to be confused with a confidence interval!). Here, we first compute the Cohen’s <em>D</em> using the first group’s variance (= 1):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># positive</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>((<span class="sc">-</span>.<span class="dv">216</span>) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># negative</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>((.<span class="dv">086</span>) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.086</code></pre>
</div>
</div>
<p>Next, we compute the Cohen’s <em>D</em> using the second group’s variance estimates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># positive</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>((<span class="sc">-</span>.<span class="dv">216</span>) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(.<span class="dv">973</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.2189764</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># negative</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>((.<span class="dv">086</span>) <span class="sc">-</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(.<span class="dv">967</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08745511</code></pre>
</div>
</div>
<p>So, depending on the standardizer (which variance) used, the Cohen’s <em>D</em> for positive financial well-being is approximately -.217 to -.219, and the Cohen’s <em>D</em> for negative financial well-being is approximately .086 to .087. Note that the ranges here are really narrow because the variances are so similar, the range would be larger if the difference in the variances was larger.</p>
</section>
</section>
<section id="summary" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.9</span> Summary</h2>
<p>In this R lab, you were introduced to the steps involved in measurement invariance testing, an important quantitative method that can help us collect evidence regarding the fairness of our measurement scale. You also learned how to compare means of latent variables, using several different approaches. This is the final R lab of this class!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./reliability.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reliability</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Copyright 2024, Sonja D. Winter</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>